javajni.so:javajni.o
	gcc -I/home/k/opt/jdk1.8.0_171/include -I/home/k/opt/jdk1.8.0_171/include/linux -shared -o javajni.so javajni.o
javajni.o:javajni.c
	gcc -I/home/k/opt/jdk1.8.0_171/include -I/home/k/opt/jdk1.8.0_171/include/linux -c -fPIC -o javajni.o javajni.c
