version: "3"
services:
  kafka0:
    image: kafka_custom:latest
    container_name: kafka0
    environment:
      - ZOOKEEPER_CONNS=zk1:2181,zk2:2181,zk3:2181
      - BROKER_ID=0
    ports:
      - 9092:9092
    networks:
      - net_custom

  kafka1:
    image: kafka_custom:latest
    container_name: kafka1
    environment:
      - ZOOKEEPER_CONNS=zk1:2181,zk2:2181,zk3:2181
      - BROKER_ID=1
    ports:
      - 9093:9092
    networks:
      - net_custom

  kafka2:
    image: kafka_custom:latest
    container_name: kafka2
    environment:
      - ZOOKEEPER_CONNS=zk1:2181,zk2:2181,zk3:2181
      - BROKER_ID=2
    ports:
      - 9094:9092
    networks:
      - net_custom

networks:
  net_custom:
    driver: bridge
