server:
  port: 8761

spring:
  application:
    name: eurka-server

eureka:
#erureka server也是一个eureka client
#eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/