version: "3"
services:
  zookeeper1:
    image: zookeeper_custom:latest
    container_name: zk1
    environment:
      - MYID=1
      - SERVER_1=server.1=zk1:2888:3888
      - SERVER_2=server.2=zk2:2888:3888
      - SERVER_3=server.3=zk3:2888:3888
    ports:
      - 2181:2181
    networks:
      - net_custom

  zookeeper2:
    image: zookeeper_custom:latest
    container_name: zk2
    environment:
      - MYID=2
      - SERVER_1=server.1=zk1:2888:3888
      - SERVER_2=server.2=zk2:2888:3888
      - SERVER_3=server.3=zk3:2888:3888
    ports:
      - 2182:2181
    networks:
      - net_custom

  zookeeper3:
    image: zookeeper_custom:latest
    container_name: zk3
    environment:
      - MYID=3
      - SERVER_1=server.1=zk1:2888:3888
      - SERVER_2=server.2=zk2:2888:3888
      - SERVER_3=server.3=zk3:2888:3888
    ports:
      - 2183:2181
    networks:
      - net_custom

networks:
  net_custom:
    driver: bridge
