version: "3"
services:
  journalnode1:
    image: hadoop_hdfs_journalnode_custom:latest
    container_name: hadoop_hdfs_journalnode1
    networks:
      - net_custom
  journalnode2:
    image: hadoop_hdfs_journalnode_custom:latest
    container_name: hadoop_hdfs_journalnode2
    networks:
      - net_custom
  journalnode3:
    image: hadoop_hdfs_journalnode_custom:latest
    container_name: hadoop_hdfs_journalnode3
    networks:
      - net_custom

networks:
  net_custom:
    driver: bridge
