version: "3"
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    ports:
      - 90:80
    environment:
      - PMA_HOST=rm-bp191x99in7ufjj09.mysql.rds.aliyuncs.com
