version: "3"
services:
  namenode1:
    image: hadoop_hdfs_namenode_custom:latest
    container_name: hadoop_hdfs_namenode1
    environment:
      - ZOOKEEPER_CONNS=zk1:2181,zk2:2181,zk3:2181
      - JOURNAL_CONNS=hadoop_hdfs_journalnode1:8485;hadoop_hdfs_journalnode2:8485;hadoop_hdfs_journalnode3:8485
      - CLUSTER_NAME=cluter1
      - CLUSTERS=cluster1:hadoop_hdfs_namenode1,hadoop_hdfs_namenode2;cluster2:hadoop_hdfs_namenode3,hadoop_hdfs_namenode4
    networks:
      - net_custom

  namenode2:
    image: hadoop_hdfs_namenode_custom:latest
    container_name: hadoop_hdfs_namenode2
    environment:
      - ZOOKEEPER_CONNS=zk1:2181,zk2:2181,zk3:2181
      - JOURNAL_CONNS=hadoop_hdfs_journalnode1:8485;hadoop_hdfs_journalnode2:8485;hadoop_hdfs_journalnode3:8485
      - CLUSTER_NAME=cluter1
      - CLUSTERS=cluster1:hadoop_hdfs_namenode1,hadoop_hdfs_namenode2;cluster2:hadoop_hdfs_namenode3,hadoop_hdfs_namenode4
    networks:
      - net_custom

  namenode3:
    image: hadoop_hdfs_namenode_custom:latest
    container_name: hadoop_hdfs_namenode3
    environment:
      - ZOOKEEPER_CONNS=zk1:2181,zk2:2181,zk3:2181
      - JOURNAL_CONNS=hadoop_hdfs_journalnode1:8485;hadoop_hdfs_journalnode2:8485;hadoop_hdfs_journalnode3:8485
      - CLUSTER_NAME=cluter2
      - CLUSTERS=cluster1:hadoop_hdfs_namenode1,hadoop_hdfs_namenode2;cluster2:hadoop_hdfs_namenode3,hadoop_hdfs_namenode4
    networks:
      - net_custom

  namenode4:
    image: hadoop_hdfs_namenode_custom:latest
    container_name: hadoop_hdfs_namenode4
    environment:
      - ZOOKEEPER_CONNS=zk1:2181,zk2:2181,zk3:2181
      - JOURNAL_CONNS=hadoop_hdfs_journalnode1:8485;hadoop_hdfs_journalnode2:8485;hadoop_hdfs_journalnode3:8485
      - CLUSTER_NAME=cluter2
      - CLUSTERS=cluster1:hadoop_hdfs_namenode1,hadoop_hdfs_namenode2;cluster2:hadoop_hdfs_namenode3,hadoop_hdfs_namenode4
    networks:
      - net_custom


networks:
  net_custom:
    driver: bridge
