server:
  port: 8091

spring:
  application:
    name: spring-cloud-eureka-consumer-based-on-feign


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #不进行注册，表明只是一个consumer
    register-with-eureka: false

