server:
  port: 8082

spring:
  application:
    name: application-b
  zipkin:
##docker 容器名字
    base-url: http://zipkin-server:9411


eureka:
  client:
    serviceUrl:
#eureka的地址为docker容器名
      defaultZone: http://eureka-server:8761/eureka/

