foo: localDefaultValue
genericKey: testDefaultValue
applicationKey: customDefaultValue
server:
  port: 8100
#http://localhost:8088/actuator/refresh,手动刷新配置（post请求）
#http://localhost:8088/actuator可以查看开启了哪些功能（get请求）
management:
  endpoints:
    web:
      exposure:
        include: refresh
spring:
  application:
    name: applicationA