# Spring boot application
spring:
  application:
    name: dubbo-provider-demo


##################### Dubbo Config #############
dubbo:
  application: # ApplicationConfig Bean
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  protocol: # ProtocolConfig Bean
    id: dubbo
    name: dubbo
    port: 12345
  registry: # RegistryConfig Bean
    id: my-registry
    address: zookeeper://127.0.0.1:2182
