# Spring boot application
spring:
  application:
    name: dubbo-provider-demo


##################### Dubbo Config #############
dubbo:
  scan:  # Base packages to scan Dubbo Components (e.g @Service , @Reference)
    base-packages: com.alibaba.boot.dubbo.demo.provider.service
  application: # ApplicationConfig Bean
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  protocol: # ProtocolConfig Bean
    id: dubbo
    name: dubbo
    port: 12345
  registry: # RegistryConfig Bean
    id: my-registry
    address: zookeeper://localhost:2181

