version: "3"
services:
  datanode1:
    image: hadoop_hdfs_datanode_custom:latest
    container_name: datanode1
    environment:
      - NAME_SERVICES=nameservice1:namenode1,namenode2;nameservice2:namenode3,namenode4
    networks:
      - net_custom

  datanode2:
    image: hadoop_hdfs_datanode_custom:latest
    container_name: datanode2
    environment:
      - NAME_SERVICES=nameservice1:namenode1,namenode2;nameservice2:namenode3,namenode4
    networks:
      - net_custom

  datanode3:
    image: hadoop_hdfs_datanode_custom:latest
    container_name: datanode3
    environment:
      - NAME_SERVICES=nameservice1:namenode1,namenode2;nameservice2:namenode3,namenode4
    networks:
      - net_custom

networks:
  net_custom:
    driver: bridge
